MvcProjeKampi/MvcProjeKampi/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using PagedList;
using PagedList.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterController : Controller
    {
        // GET: Writer

        WriterManager wm = new WriterManager(new EFWriterDal());
        WriterValidator writerValidator = new WriterValidator();

        [Authorize]
        public ActionResult Index(int pager = 1)
        {
            var WriterValues = wm.GetList().ToPagedList(pager, 8);
            return View(WriterValues);
        }

        [HttpGet]
        public ActionResult AddWriter()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddWriter(Writer wr)
        {
            ValidationResult results = writerValidator.Validate(wr);  

            if (results.IsValid)  //Validasyon kontrolleri sağlanır ve koşullar uyumluysa
            {
                wm.WriterAddBL(wr); //ekleme işlemini yap
                return RedirectToAction("Index");

            }
            else
            {
                foreach (var item in results.Errors) // değilse
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);  // hata mesajı döndür
                }
            }

            return View();
        }


        public ActionResult DeleteWriter(int id)
        {
            var WriterValues = wm.GetByID(id);
            wm.WriterDeleteBL(WriterValues);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditWriter(int id)
        {
            var WriterValues = wm.GetByID(id);
            return View(WriterValues);
        }

        [HttpPost]
        public ActionResult EditWriter(Writer wr)
        {

            ValidationResult results = writerValidator.Validate(wr);

            if (results.IsValid)  //Validasyon kontrolleri sağlanır ve koşullar uyumluysa
            {
                wm.WriterUpdateBL(wr); //ekleme işlemini yap
                return RedirectToAction("Index");

            }
            else
            {
                foreach (var item in results.Errors) // değilse
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);  // hata mesajı döndür
                }
            }
            return View();

        }
    }
}

MvcProjeKampi/MvcProjeKampi/Views/Writer/AddWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "AddWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h3>Yeni yazar ekleme sayfası</h3>
<br />

@using (Html.BeginForm("AddWriter", "Writer", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Yazar Adı")
    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterName)
    <br />
    @Html.Label("Yazar Soyadı")
    @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterSurName)
    <br />
    @Html.Label("Yazar Resim Linki")
    @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterImage)
    <br />
    @Html.Label("Yazar Mail")
    @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterMail)
    <br />
    @Html.Label("Yazar Ünvanı")
    @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterTitle)
    <br />
    @Html.Label("Yazar Hakkında")
    @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterAbout)
    <br />
    @Html.Label("Yazar Şifresi")
    @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterPassword)
    <br /><br />
    <button class="btn btn-success">Yazarı Ekle</button>
</div>
}

MvcProjeKampi/MvcProjeKampi/Views/Writer/EditWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "EditWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h3>Yazar Bilgileri Düzenleme Formu</h3>
<br />

@using (Html.BeginForm("EditWriter", "Writer", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Yazar ID")
    @Html.TextBoxFor(x => x.WriterID, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar Adı")
    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterName)
    <br />
    @Html.Label("Yazar Soyadı")
    @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterSurName)
    <br />
    @Html.Label("Yazar Resim Linki")
    @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterImage)
    <br />
    @Html.Label("Yazar Mail")
    @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterMail)
    <br />
    @Html.Label("Yazar Ünvanı")
    @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterTitle)
    <br />
    @Html.Label("Yazar Hakkında")
    @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterAbout)
    <br />
    @Html.Label("Yazar Şifresi")
    @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterPassword)
    <br /><br />
    <button class="btn btn-success">Yazarı Güncelle</button>
</div>
}

MvcProjeKampi/MvcProjeKampi/Views/Writer/Index.cshtml
@using EntityLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Writer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yazarlar Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-3 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                    @item.WriterTitle
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7" style="width:250px">
                                            <h2 class="lead"><b>@item.WriterName @item.WriterSurName</b></h2>
                                            <p class="text-muted text-sm"><b>Hakkında: </b> @item.WriterAbout </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-envelope"></i></span> Mail: @item.WriterMail</li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            @*<img src="~/Templates/AdminLTE-3.0.4/dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">*@
                                            <img src="@item.WriterImage" alt="" class="img-circle img-fluid" style="width:75px; height:75px">

                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="#" class="btn btn-sm bg-teal">
                                            <i class="fas fa-pen"></i>  Yazarın Başlıkları
                                        </a>
                                        <a href="/Writer/EditWriter/@item.WriterID" class="btn btn-sm btn-primary">
                                            <i class="fas fa-user"></i> Profili Düzenle
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    <br /><br />
                </div>
            </div>
        </div>
        <div class="card-footer">
            <nav aria-label="Contacts Page Navigation">
                <ul class="pagination justify-content-center m-0">
                    @Html.PagedListPager((IPagedList)Model, pager => Url.Action("Index", new { pager }), new PagedListRenderOptions
    {
    LiElementClasses = new List<string>
    { "page-link"}
    })
                </ul>
            </nav>
        </div>
        <!-- /.card -->
        <a href="/Writer/AddWriter/" class="btn btn-sm btn-success"> <i class="fas fa-plus"></i> Yeni Yazar Ekle</a>

    </section>
    <!-- /.content -->
</body>
</html>