MvcProjeKampi/MvcProjeKampi/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterPanelContentController : Controller
    {
        // GET: WriterPanelContent
        ContentManager cm = new ContentManager(new EFContentDal());
        Context context = new Context();
        public ActionResult MyContent()
        {
            string p = (string)Session["WriterMail"];
            var writerIdInfo = context.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            var contentvalue = cm.GetListByWriter(writerIdInfo);
            return View(contentvalue);
        }


        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content c)
        {
            string mail = (string)Session["WriterMail"];
            var writerIdInfo = context.Writers.Where(x => x.WriterMail == mail).Select(y => y.WriterID).FirstOrDefault();

            c.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.WriterID = writerIdInfo;
            c.ContentStatus = true;
            cm.ContentAddBL(c);
            return RedirectToAction("MyContent");
        }


    }
}

MvcProjeKampi/MvcProjeKampi/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Yeni İçerik Ekle</h2>

@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
    <div class="form-group">

        <input type="hidden" name="HeadingID" value="@ViewBag.d" style="display:none;" />
        @Html.Label("İçeriğinizi Yazın")
        @Html.TextAreaFor(x => x.ContentValue, 4, 30, new { @class = "form-control mt-2", @placeholder = "İçerik Girin" })
        @Html.ValidationMessageFor(x => x.ContentValue, "", new { @class = "text-danger  mt-2" })
        <button class="btn btn-danger mt-2"><i class="fas fa-save mr-2"></i>İçerik Ekle</button>
    </div>
}

MvcProjeKampi/MvcProjeKampi/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                            }

                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>