MvcProjeKampi/MvcProjeKampi/Controllers/WriterPanelMessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterPanelMessageController : Controller
    {
        // GET: WriterPanelMessage
        MessageManager mm = new MessageManager(new EFMessageDal());
        MessageValidator mv = new MessageValidator();

        public ActionResult WriterPanelInbox()
        {
            string p = (string)Session["WriterMail"];
            var messageList = mm.GetListInbox(p);
            return View(messageList);
        }
        

        public ActionResult WriterPanelSendbox()
        {
            string p = (string)Session["WriterMail"];
            var messageList = mm.GetListSendbox(p);
            return View(messageList);
        }

        public ActionResult GetWriterInboxDetails(int id)
        {
            var value = mm.GetByID(id);
            return View(value);
        }
        public ActionResult GetWriterSendboxDetails(int id)
        {
            var value = mm.GetByID(id);
            return View(value);
        }

        [HttpGet]
        public ActionResult WriterNewMessage()
        {
            return View();
        }

        [HttpPost]
        //[ValidateInput(false)]

        public ActionResult WriterNewMessage(Message message)
        {

            ValidationResult result = mv.Validate(message);
            if (result.IsValid)
            {
                string sender = (string)Session["WriterMail"];
                message.SenderMail = sender;
                message.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                mm.MessageAddBL(message);
                return RedirectToAction("WriterPanelSendbox");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

            }
            return View();
        }

        public PartialViewResult WriterMessageListMenu()
        {
            string p = (string)Session["WriterMail"];
            ViewBag.a2 = mm.GetListInbox(p).Count();
            ViewBag.a3 = mm.GetListSendbox(p).Count();
            return PartialView();
        }

        //checbox ile toplu silme işlemi için
        [HttpPost]
        public ActionResult DeleteSelectedWriterInbox(List<int> ids)
        {
            if (ids != null && ids.Any())
            {
                foreach (var id in ids)
                {
                    var message = mm.GetByID(id);
                    if (message != null)
                    {
                        mm.MessageDeleteBL(message);
                    }
                }
            }
            return RedirectToAction("WriterPanelInbox");
        }


        //checbox ile toplu silme işlemi için
        [HttpPost]
        public ActionResult DeleteSelectedWriterSendbox(List<int> ids)
        {
            if (ids != null && ids.Any())
            {
                foreach (var id in ids)
                {
                    var message = mm.GetByID(id);
                    if (message != null)
                    {
                        mm.MessageDeleteBL(message);
                    }
                }
            }
            return RedirectToAction("WriterPanelSendbox");
        }


        public ActionResult DeleteWriterInboxDetails(int id)
        {
            var messageValues = mm.GetByID(id);
            mm.MessageDeleteBL(messageValues);
            return RedirectToAction("WriterPanelInbox");
        }


        public ActionResult DeleteWriterSendboxDetails(int id)
        {
            var messageValues = mm.GetByID(id);
            mm.MessageDeleteBL(messageValues);
            return RedirectToAction("WriterPanelSendbox");
        }
    }
}

MvcProjeKampi/MvcProjeKampi/Views/WriterPanelMessage/GetWriterInboxDetails.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "GetWriterInboxDetails";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Gelen Mesaj Detayları</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">

            <div class="row">

                @Html.Action("WriterMessageListMenu", "WriterPanelMessage")
                <!-- /.col -->

                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h2 class="card-title">Mesaj İçeriği</h2>

                            <div class="card-tools">
                                <a class="btn btn-danger" href="/WriterPanelMessage/WriterPanelInbox/"> <i class="fas fa-reply"></i>@Html.ValueFor(x => x.Subject)</a>

                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5><b>Konu:</b> @Html.ValueFor(x => x.Subject)</h5>
                                <br />
                                <h6>
                                    <b>Kimden:</b> @Html.ValueFor(x => x.SenderMail) <br />
                                    <b>Alıcı:</b> @Html.ValueFor(x => x.ReceiverMail)
                                    <span class="mailbox-read-time float-right">@DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToShortDateString();</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>
                                    @Html.ValueFor(x => x.MessageContent)
                                </p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-body -->
                        <!-- /.card-footer -->
                        <div class="card-footer">
                            <div class="float-right">
                                <button type="button" class="btn btn-default"><i class="fas fa-reply"></i> Reply</button>
                                <button type="button" class="btn btn-default"><i class="fas fa-share"></i> Forward</button>
                            </div>
                            <a href="@Url.Action("DeleteWriterInboxDetails", "WriterPanelMessage", new { id = Model.MessageID })" class="btn btn-default">
                                <i class="far fa-trash-alt"></i> Mesajı Sil
                            </a>
                            <button type="button" class="btn btn-default"><i class="fas fa-print"></i> Print</button>
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>

</body>
</html>

MvcProjeKampi/MvcProjeKampi/Views/WriterPanelMessage/GetWriterSendboxDetails.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "GetWriterSendboxDetails";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Gönderilen Mesaj Detayları</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">

            <div class="row">

                @Html.Action("WriterMessageListMenu", "WriterPanelMessage")
                <!-- /.col -->

                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h2 class="card-title">Mesaj İçeriği</h2>

                            <div class="card-tools">
                                <a class="btn btn-danger" href="/WriterPanelMessage/WriterPanelSendbox/"> <i class="fas fa-reply"></i>@Html.ValueFor(x => x.Subject)</a>

                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5><b>Konu:</b> @Html.ValueFor(x => x.Subject)</h5>
                                <br />
                                <h6>
                                    <b>Kimden:</b> @Html.ValueFor(x => x.SenderMail) <br />
                                    <b>Alıcı:</b> @Html.ValueFor(x => x.ReceiverMail)
                                    <span class="mailbox-read-time float-right">@DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToShortDateString();</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>
                                    @Html.ValueFor(x => x.MessageContent)
                                </p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-body -->
                        <!-- /.card-footer -->
                        <div class="card-footer">
                            <div class="float-right">
                                <button type="button" class="btn btn-default"><i class="fas fa-reply"></i> Reply</button>
                                <button type="button" class="btn btn-default"><i class="fas fa-share"></i> Forward</button>
                            </div>
                            <a href="@Url.Action("DeleteWriterSendboxDetails", "WriterPanelMessage", new { id = Model.MessageID })" class="btn btn-default">
                                <i class="far fa-trash-alt"></i> Mesajı Sil
                            </a>
                            <button type="button" class="btn btn-default"><i class="fas fa-print"></i> Print</button>
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>

</body>
</html>

MvcProjeKampi/MvcProjeKampi/Views/WriterPanelMessage/WriterMessageListMenu.cshtml
<div class="col-md-3">
    <a href="/WriterPanelMessage/WriterNewMessage/" class="btn btn-primary btn-block mb-3">Mesaj Oluştur</a>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Seçenekler</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <ul class="nav nav-pills flex-column">
               
                <li class="nav-item active">
                    <a href="/WriterPanelMessage/WriterPanelInbox/" class="nav-link">
                        <i class="fas fa-inbox"></i> Gelen Mesajlar
                        <span class="badge bg-primary float-right">@ViewBag.a2</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/WriterPanelMessage/WriterPanelSendbox/" class="nav-link">
                        <i class="far fa-envelope"></i> Gönderilen Mesajlar
                        <span class="badge bg-primary float-right">@ViewBag.a3</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-file-alt"></i> Taslaklar
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fas fa-filter"></i> Spam
                        <span class="badge bg-warning float-right">65</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-trash-alt"></i> Çöp Kutusu
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Diğer</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-circle text-danger"></i>
                        Önemli Olanlar
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-circle text-warning"></i> Tanıtımlar
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-circle text-primary"></i>
                        Sosyal Medya
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

MvcProjeKampi/MvcProjeKampi/Views/WriterPanelMessage/WriterNewMessage.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "WriterNewMessage";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/Templates/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/Templates/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yeni Mesaj Oluşturma Sayfası</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("WriterMessageListMenu", "WriterPanelMessage")
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm("WriterNewMessage", "WriterPanelMessage", FormMethod.Post))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Yeni Mesaj Oluştur</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                             
                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.ReceiverMail, new { @class = "form-control mt-2", @placeholder = "Kime:" })
                                    @Html.ValidationMessageFor(x => x.ReceiverMail, "", new { @class = "text-danger  mt-2" })
                                </div>
                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control mt-2", @placeholder = "Konu:" })
                                    @Html.ValidationMessageFor(x => x.Subject, "", new { @class = "text-danger  mt-2" })
                                </div>
                                <div class="form-group">
                                    @Html.TextAreaFor(x => x.MessageContent, new { @class = "form-control", @placeholder = "Mesajınız:" })
                                    @Html.ValidationMessageFor(x => x.MessageContent, "", new { @class = "text-danger  mt-2" })
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet</button>
                                    <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Mesajı Gönder</button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                    }
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Templates/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Templates/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Templates/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Summernote -->
    <script src="~/Templates/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- Page Script -->
    <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote()
        })</script>
</body>
</html>

MvcProjeKampi/MvcProjeKampi/Views/WriterPanelMessage/WriterPanelInbox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "WriterPanelInbox";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Gelen Mesajlar Sayfası</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="row">
            @Html.Action("WriterMessageListMenu", "WriterPanelMessage")

            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Mail- Gelen Kutusu</h3>

                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <!-- /.btn-group -->
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>
                                            <div class="icheck-primary">
                                                <input type="checkbox" value="@item.MessageID" id="check@item.MessageID" class="message-checkbox">
                                                <label for="check@item.MessageID"></label>
                                            </div>
                                        </td>
                                        <td class="mailbox-star"><a href="/WriterPanelMessage/GetWriterInboxDetails/@item.MessageID"><i class="fas fa-star text-warning"></i></a></td>
                                        <td class="mailbox-name"><a href="/WriterPanelMessage/GetWriterInboxDetails/@item.MessageID">@item.SenderMail</a></td>
                                  
                                        <td class="mailbox-subject">
                                            <b>@item.Subject</b> - @(item.MessageContent.Length > 30 ? item.MessageContent.Substring(0, 30) + "..." : item.MessageContent)
                                        </td>

                                     
                                        <td class="mailbox-attachment"></td>
                                        <td class="mailbox-date">@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy hh:mm"))</td>
                                    </tr>

                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" id="delete-selected-button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>


</body>
</html>
<script>
    $(function () {
        //Enable check and uncheck all functionality
        $('.checkbox-toggle').click(function () {
            var clicks = $(this).data('clicks')
            if (clicks) {
                //Uncheck all checkboxes
                $('.mailbox-messages input[type="checkbox"]').prop('checked', false)
                $('.checkbox-toggle .far.fa-check-square').removeClass('fa-check-square').addClass('fa-square')
            } else {
                //Check all checkboxes
                $('.mailbox-messages input[type="checkbox"]').prop('checked', true)
                $('.checkbox-toggle .far.fa-square').removeClass('fa-square').addClass('fa-check-square')
            }
            $(this).data('clicks', !clicks)
        })

        //Handle starring for glyphicon and font awesome
        $('.mailbox-star').click(function (e) {
            e.preventDefault()
            //detect type
            var $this = $(this).find('a > i')
            var glyph = $this.hasClass('glyphicon')
            var fa = $this.hasClass('fa')

            //Switch states
            if (glyph) {
                $this.toggleClass('glyphicon-star')
                $this.toggleClass('glyphicon-star-empty')
            }

            if (fa) {
                $this.toggleClass('fa-star')
                $this.toggleClass('fa-star-o')
            }
        })
    })

    function getSelectedMessageIds() {
        var selected = [];
        document.querySelectorAll('.message-checkbox:checked').forEach(function (checkbox) {
            selected.push(checkbox.value);
        });
        return selected;
    }

    function deleteSelectedMessages() {
        var selectedIds = getSelectedMessageIds();
        if (selectedIds.length > 0) {
            // Send selectedIds to the server
            fetch('/WriterPanelMessage/DeleteSelectedWriterInbox', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ ids: selectedIds })
            })
                .then(response => {
                    if (response.ok) {
                        window.location.reload();
                    } else {
                        alert('Bir hata oluştu, lütfen tekrar deneyin.');
                    }
                });
        } else {
            alert('Lütfen silmek istediğiniz mesajları seçin.');
        }
    }

    document.getElementById('delete-selected-button').addEventListener('click', deleteSelectedMessages);
</script>



<!-- jQuery -->
<script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/Templates/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="~/Templates/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
<!-- Page Script -->
<!-- AdminLTE for demo purposes -->
<script src="~/Templates/AdminLTE-3.0.4/dist/js/demo.js"></script>